/** Patterns flagged during static analysis of script content (logged, not blocked). */
export const SUSPICIOUS_PATTERNS: RegExp[] = [
  /document\.cookie/gi,
  /localStorage/gi,
  /sessionStorage/gi,
  /window\.location\s*=/gi,
  /window\.open\s*\(/gi,
  /navigator\.sendBeacon/gi,
  /new\s+WebSocket/gi,
  /importScripts/gi,
  /XMLHttpRequest/gi,
  /\.src\s*=\s*['"`]https?:/gi,
];

/** DOMPurify config: preserves script/style but strips XSS vectors. */
export const DOMPURIFY_CONFIG = {
  ALLOWED_TAGS: [
    'html', 'head', 'body', 'div', 'span', 'p', 'a', 'img', 'br', 'hr',
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
    'table', 'thead', 'tbody', 'tfoot', 'tr', 'th', 'td', 'caption', 'colgroup', 'col',
    'ul', 'ol', 'li', 'dl', 'dt', 'dd',
    'strong', 'em', 'b', 'i', 'u', 'sub', 'sup', 'small', 'mark', 'del', 'ins',
    'pre', 'code', 'blockquote', 'abbr', 'cite', 'q',
    'header', 'footer', 'nav', 'main', 'section', 'article', 'aside',
    'figure', 'figcaption', 'details', 'summary', 'time', 'address',
    'canvas',
    'svg', 'path', 'circle', 'rect', 'line', 'polyline', 'polygon',
    'ellipse', 'g', 'text', 'tspan', 'defs', 'clipPath', 'use', 'symbol',
    'linearGradient', 'radialGradient', 'stop', 'mask', 'pattern',
    'foreignObject', 'image',
    'style',
    'script',
    'link',
    'meta',
    'title',
    'label', 'input', 'select', 'option', 'textarea', 'fieldset', 'legend',
  ],
  ALLOWED_ATTR: [
    'class', 'id', 'style', 'src', 'href', 'alt', 'title', 'width', 'height',
    'colspan', 'rowspan', 'scope', 'role', 'aria-*',
    'viewBox', 'xmlns', 'xmlns:xlink', 'd', 'fill', 'stroke', 'stroke-width',
    'stroke-dasharray', 'stroke-linecap', 'stroke-linejoin',
    'transform', 'opacity', 'fill-opacity', 'stroke-opacity',
    'cx', 'cy', 'r', 'rx', 'ry', 'x', 'y', 'x1', 'y1', 'x2', 'y2',
    'points', 'font-size', 'font-family', 'font-weight',
    'text-anchor', 'dominant-baseline', 'text-decoration',
    'offset', 'stop-color', 'stop-opacity', 'gradientUnits', 'gradientTransform',
    'patternUnits', 'patternTransform', 'preserveAspectRatio',
    'data-*',
    'charset', 'name', 'content', 'type', 'rel', 'media',
    'value', 'placeholder', 'disabled', 'readonly', 'checked', 'selected',
    'for', 'rows', 'cols', 'maxlength', 'min', 'max', 'step',
  ],
  FORBID_ATTR: [
    'onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover',
    'onmouseout', 'onmousemove', 'onmouseenter', 'onmouseleave',
    'onkeydown', 'onkeyup', 'onkeypress',
    'onfocus', 'onblur', 'onchange', 'oninput', 'onsubmit', 'onreset',
    'onload', 'onerror', 'onabort', 'onresize', 'onscroll',
    'oncontextmenu', 'ondrag', 'ondrop', 'oncopy', 'oncut', 'onpaste',
    'onanimationstart', 'onanimationend', 'onanimationiteration',
    'ontransitionend', 'ontouchstart', 'ontouchend', 'ontouchmove',
    'onpointerdown', 'onpointerup', 'onpointermove',
    'formaction', 'action',
  ],
  FORBID_TAGS: ['iframe', 'object', 'embed', 'applet', 'form'],
  ALLOW_UNKNOWN_PROTOCOLS: false,
  WHOLE_DOCUMENT: true,
  FORCE_BODY: false,
};
